apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env-config
data:
  APP_ENV: develop
  APP_TYPE: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      
      location /secure {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/htpasswd/htpasswd;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  htpasswd: YWRtaW46JGFwcjEkc2s1VUFuUXF2dDhHaW5jL3huMnhPVmVvLjFHaVJ6CiA=
  # user: admin , password admin123.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: secret-volume
        secret:
          secretName: nginx-secret
      containers:
      - name: nginx
        image: nginx:1.25
        envFrom:
        - configMapRef:
            name: nginx-env-config
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/
        - name: secret-volume
          mountPath: /etc/nginx/htpasswd
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nginx.devops.cl
  rules:
  - host: nginx.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - host: pruebas.devops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
